86cwau15y - feat: support unmarshal decimal in AppPlanV2
gempages/go-shopify-graphql-model pull request #16
Opened 2024-10-03 09:42 UTC by violettran

## What's changed
- Supported unmarshal decimal in AppPlanV2.

2024-10-03 11:47 UTC, vincentluan requested changes

2024-10-03 11:47 UTC, vincentluan commented on graph/model/types.go
> +	AppUsagePricingTypeName               = "AppUsagePricing"
Tạo ra 1 type tên là `GqlTypeName`. Mỗi biến này sẽ thuộc type đó và bỏ chữ `TypeName` trong tên biến đi

2024-10-03 11:47 UTC, vincentluan commented on graph/model/unmarshal.go
> +		formatAppRecurringPricingDetails(data)
Nguyên tắc là không dùng input argument làm return variable. Đổi thành `data = ...`

2024-10-04 02:02 UTC, violettran commented on graph/model/types.go
> +	AppUsagePricingTypeName               = "AppUsagePricing"
Trong package có tên struct trùng với tất cả string ở trên nên em mới phải thêm suffix `TypeName` cho chúng.

2024-10-05 04:23 UTC, vincentluan requested changes

2024-10-07 03:03 UTC, vincentluan approved these changes

2024-10-07 03:03 UTC, merged